trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Preparation
    displayName: 'Preparation Stage'
    jobs:
      - job: CheckoutAndPrepare
        displayName: 'Checkout and Prepare Analysis'
        steps:
          - checkout: self
            fetchDepth: 0

          - task: SonarCloudPrepare@2
            displayName: 'Prepare SonarCloud analysis'
            inputs:
              SonarCloud: 'sonar'
              organization: 'arvadde'
              scannerMode: 'Other'
              extraProperties: |
                sonar.projectKey=arvadde_snowdevops
                sonar.projectName=snowdevops

  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildPackage
        displayName: 'Build and Package'
        steps:
          - task: Maven@3
            displayName: 'Build with Maven'
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'
              jdkArchitectureOption: 'x64'
              goals: 'package'

  - stage: Test
    displayName: 'Test Stage'
    jobs:
      - job: TestPublish
        displayName: 'Test and Publish Results'
        steps:
          - task: Maven@3
            displayName: 'Test with Maven and Publish Results'
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: 'test'

  - stage: Analysis
    displayName: 'Analysis Stage'
    jobs:
      - job: SonarAnalysis
        displayName: 'SonarQube Analysis'
        steps:
          - task: Maven@3
            displayName: 'SonarQube Analysis'
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'
              jdkArchitectureOption: 'x64'
              goals: 'sonar:sonar'
              sonarQubeRunAnalysis: true
              sqMavenPluginVersionChoice: 'pom'