trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildAndPackage
    displayName: 'Build and Package'
    jobs:
      - job: BuildJob
        displayName: 'Build Maven Project'
        steps:
          - checkout: self
            fetchDepth: 0

          - task: Maven@3
            displayName: 'Build with Maven'
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'
              jdkArchitectureOption: 'x64'
              goals: 'package'

  - stage: Test
    displayName: 'Test'
    jobs:
      - job: TestJob
        displayName: 'Run Tests and Publish Results'
        steps:
          - task: Maven@3
            displayName: 'Test with Maven and Publish Results'
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: 'test'

  - stage: changeCreation
    displayName: 'Change creation'
    pool:
      name: Server
    jobs:
      - job: changecreation
        displayName: 'Change creation'
        steps:
          - task: ServiceNow-DevOps-Server-Change-Acceleration@1
            inputs:
              connectedServiceName: 'operateedgedev-snowdevops-ServiceNow DevOps Service Connection'
              changeRequestDetails: |
                {
                    "setCloseCode" : true,
                    "autoCloseChange" : true,
                    "attributes": {
                      "requested_by": {
                        "name": "Aravind Vadde"
                      },
                "short_description":"Software Deployment for Servicenow Devops POC",
                "description":"Software Deployment.",
                "assignment_group":"DevOps Report",
                "implementation_plan":"Software update is tested and results can be found in Test Summaries Tab.",
                "backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed or not",
                "justification":"justification",
                      "start_date": "2025-01-05 08:00:00",
                      "end_date": "2025-01-08 08:00:00"
                    }
                  }
  
  - stage: SonarPrepAndAnalysis
    displayName: 'SonarQube Preparation and Analysis'
    jobs:
      - job: SonarJob
        displayName: 'Prepare and Analyze with SonarQube'
        steps:
          - task: SonarCloudPrepare@2
            displayName: 'Prepare SonarCloud analysis'
            inputs:
              SonarCloud: 'sonar'
              organization: 'arvadde'
              scannerMode: 'Other'
              extraProperties: |
                sonar.projectKey=arvadde_snowdevops
                sonar.projectName=snowdevops

          - task: Maven@3
            displayName: 'SonarQube Analysis'
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'
              jdkArchitectureOption: 'x64'
              goals: 'sonar:sonar'
              sonarQubeRunAnalysis: true
              sqMavenPluginVersionChoice: 'pom'