pr:
- main
- releases/*

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildAndPackage
    displayName: 'Build and Package'
    jobs:
      - job: BuildJob
        displayName: 'Build Maven Project'
        steps:
          - checkout: self
            fetchDepth: 0

          - task: Maven@3
            displayName: 'Build with Maven'
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'
              jdkArchitectureOption: 'x64'
              goals: 'package'

  - stage: Test
    displayName: 'Test'
    jobs:
      - job: TestJob
        displayName: 'Run Tests and Publish Results'
        steps:
          - task: Maven@3
            displayName: 'Test with Maven and Publish Results'
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: 'test'

  - stage: changeCreation
    displayName: 'Change creation'
    pool:
      name: Server
    jobs:
      - job: changecreation
        displayName: 'Change creation'
        steps:
          - task: ServiceNow-DevOps-Server-Change-Acceleration@1
            inputs:
              connectedServiceName: 'operateedgedev-snowdevops-ServiceNow DevOps Service Connection'
              changeRequestDetails: |
                {
                    "attributes": {
                      "requested_by": {
                        "name": "Aravind Vadde"
                      },
                      "short_description":"Software Deployment for Servicenow Devops POC",
                      "description":"Software Deployment.",
                      "implementation_plan":"Software update is tested and results can be found in Test Summaries Tab.",
                      "backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed or not",
                      "justification":"Important feature rollout",
                      "service_offering": "65d429bc87580ad0ecf287bd0ebb35f8",
                      "cmdb_ci": "64af7136c36631101ad0b0b78640ddc6",
                      "assignment_group": "6fec7fdd5b40011074d09113a281c771",
                      "business_service":"38c4e5bc87580ad0ecf287bd0ebb352a",
                      "assigned_to":"a28d9732876e0254ecf287bd0ebb35a7",
                      "start_date": "2025-01-05 08:00:00",
                      "end_date": "2025-01-08 08:00:00",
                      "priority": "4"

                    }
                  }
  
  - stage: SonarPrepAndAnalysis
    displayName: 'Deployment'
    jobs:
      - job: SonarJob
        displayName: 'Deployment simulation'
        steps:
          - task: SonarCloudPrepare@2
            displayName: 'Prepare SonarCloud analysis'
            inputs:
              SonarCloud: 'sonar'
              organization: 'arvadde'
              scannerMode: 'Other'
              extraProperties: |
                sonar.projectKey=arvadde_snowdevops
                sonar.projectName=snowdevops

          - task: Maven@3
            displayName: 'SonarQube Analysis'
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'
              jdkArchitectureOption: 'x64'
              goals: 'sonar:sonar'
              sonarQubeRunAnalysis: true
              sqMavenPluginVersionChoice: 'pom'