trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  # Checkout Code
  - checkout: self
    fetchDepth: 0

  # SonarQube Preparation
  - task: SonarCloudPrepare@2
    displayName: 'Prepare SonarCloud analysis'
    inputs:
      SonarCloud: 'sonar'
      organization: 'arvadde'
      scannerMode: 'Other'
      extraProperties: |
        sonar.projectKey=arvadde_snowdevops
        sonar.projectName=snowdevops

  # Maven Build and Package
  - task: Maven@3
    displayName: 'Build with Maven'
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      jdkArchitectureOption: 'x64'
      goals: 'package'

  # Maven Test and Publish Results
  - task: Maven@3
    displayName: 'Test with Maven and Publish Results'
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'test'

  # SonarQube Analysis
  - task: Maven@3
    displayName: 'SonarQube Analysis'
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      jdkArchitectureOption: 'x64'
      goals: 'sonar:sonar'
      sonarQubeRunAnalysis: true
      sqMavenPluginVersionChoice: 'pom'