# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml


    
  changeApproval:
    name: ServiceNow Change Approval
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: ServiceNow Change
      uses: ServiceNow/servicenow-devops-change@v3.0.0
      with:
        # Devops Integration Token
        devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
        # ServiceNow Instance URL
        instance-url: ${{ secrets.SN_INSTANCE_URL }}
        # Orchestration Tool Id
        tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
        # GitHub Context
        context-github: ${{ toJSON(github) }}
        # Display Name of the Job
        job-name: 'ServiceNow DevOps Change'
        change-request: '{"attributes":{
      "parent": "",
      "reason": "",
      "watch_list": "",
      "upon_reject": "cancel",
      "sys_updated_on": "2024-06-13 18:53:28",
      "type": "normal",
      "x_dnz_connectquick_sent_attachments": "",
      "approval_history": "",
      "skills": "",
      "test_plan": "",
      "cab_delegate": "",
      "requested_by_date": "",
      "x_dgsms_operate_ai_inferred_sentiment": "",
      "state": "-5",
      "x_dgsms_operate_ai_inferred_importance": "",
      "sys_created_by": "arvadde",
      "knowledge": "false",
      "order": "",
      "phase": "requested",
      "cmdb_ci": {
        "link": "https://operateedgedev.service-now.com/api/now/v1/table/cmdb_ci/6ae88e3ec36631101ad0b0b78640dd82",
        "value": "6ae88e3ec36631101ad0b0b78640dd82"
      },
      "delivery_plan": "",
      "u_expedited": "false",
      "contract": "",
      "impact": "3",
      "active": "true",
      "work_notes_list": "",
      "priority": "4",
      "sys_domain_path": "/",
      "x_dnz_connectquick_direction_global": "",
      "x_dnz_connectquick_sequence_number_global": "",
      "cab_recommendation": "",
      "production_system": "false",
      "review_date": "",
      "business_duration": "",
      "group_list": "",
      "requested_by": "",
      "change_plan": "",
      "x_dnz_connectquick_related_integration_record_global": "",
      "approval_set": "",
      "implementation_plan": "",
      "universal_request": "",
      "end_date": "",
      "short_description": "Test",
      "x_dnz_connectquick_integration_task_type_global": "",
      "correlation_display": "",
      "delivery_task": "",
      "work_start": "",
      "additional_assignee_list": "",
      "outside_maintenance_schedule": "false",
      "std_change_producer_version": "",
      "service_offering": {
        "link": "https://operateedgedev.service-now.com/api/now/v1/table/service_offering/f6275f44533230109f88ddeeff7b127a",
        "value": "f6275f44533230109f88ddeeff7b127a"
      },
      "sys_class_name": "change_request",
      "closed_by": "",
      "follow_up": "",
      "x_dcsus_deloitte_e_project_key": "",
      "devops_change": "false",
      "u_planned_outage_downtime_required": "",
      "reassignment_count": "0",
      "review_status": "",
      "u_sla_exception_approved": "false",
      "assigned_to": "",
      "start_date": "",
      "sla_due": "",
      "comments_and_work_notes": "",
      "x_dgsms_operate_ai_inferred_urgency": "",
      "x_dgsms_operate_ai_ai_guidance": "",
      "escalation": "0",
      "upon_approval": "proceed",
      "correlation_id": "",
      "made_sla": "true",
      "backout_plan": "",
      "u_sla_exception_request": "",
      "conflict_status": "Not Run",
      "task_effective_number": "CHG0038731",
      "x_dnz_connectquick_integration_caller_global": "",
      "x_dgsms_operate_ai_ai_review": "",
      "sys_updated_by": "arvadde",
      "opened_by": {
        "link": "https://operateedgedev.service-now.com/api/now/v1/table/sys_user/a28d9732876e0254ecf287bd0ebb35a7",
        "value": "a28d9732876e0254ecf287bd0ebb35a7"
      },
      "user_input": "",
      "sys_created_on": "2024-06-13 18:53:07",
      "on_hold_task": "",
      "sys_domain": {
        "link": "https://operateedgedev.service-now.com/api/now/v1/table/domain/global",
        "value": "global"
      },
      "task_for": "",
      "route_reason": "",
      "u_inside_blackout_schedule": "false",
      "closed_at": "",
      "review_comments": "",
      "business_service": {
        "link": "https://operateedgedev.service-now.com/api/now/v1/table/cmdb_ci_service/9d4a6eb307523010a6d28bb2cfd300eb",
        "value": "9d4a6eb307523010a6d28bb2cfd300eb"
      },
      "time_worked": "",
      "chg_model": {
        "link": "https://operateedgedev.service-now.com/api/now/v1/table/chg_model/007c4001c343101035ae3f52c1d3aeb2",
        "value": "007c4001c343101035ae3f52c1d3aeb2"
      },
      "expected_start": "",
      "opened_at": "2024-06-13 18:49:41",
      "work_end": "",
      "x_dnz_connectquick_external_assignee": "",
      "phase_state": "open",
      "cab_date": "",
      "work_notes": "",
      "close_code": "",
      "assignment_group": {
        "link": "https://operateedgedev.service-now.com/api/now/v1/table/sys_user_group/d625dccec0a8016700a222a0f7900d06",
        "value": "d625dccec0a8016700a222a0f7900d06"
      },
      "description": "Test",
      "on_hold_reason": "",
      "calendar_duration": "",
      "close_notes": "",
      "sys_id": "c4e3405d47720210d1ed92e2846d4335",
      "contact_type": "",
      "cab_required": "false",
      "urgency": "3",
      "scope": "3",
      "u_message_announcement": "",
      "company": "",
      "justification": "",
      "activity_due": "",
      "comments": "",
      "approval": "not requested",
      "due_date": "",
      "sys_mod_count": "1",
      "u_release": "",
      "on_hold": "false",
      "sys_tags": "",
      "x_dnz_connectquick_integration_candidate": "false",
      "cab_date_time": "",
      "conflict_last_run": "",
      "x_dnz_connectquick_vendor_task_number_global": "",
      "risk_value": "",
      "x_dnz_connectquick_external_assignment_group_global": "",
      "unauthorized": "false",
      "x_dnz_connectquick_external_status_global": "",
      "location": "",
      "risk": "",
      "category": "DevOps",
      "x_dnz_connectquick_integration_ci_global": "",
      "risk_impact_analysis": ""
    }}'





